export const ROUTES = {
  HOME: '/',
  HOW_TO_REGISTER: '/how-to-register',
  ANNOUNCEMENTS: '/announcements',
  RANKING: '/ranking',
  LOGIN: '/login',
  ADMIN_LOGIN: '/admin/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  COMPLETE_PROFILE: '/complete-profile',
  STUDENT_DASHBOARD: '/dashboard/student',
  STUDENT_RESULTS: '/dashboard/student/results',
  STUDENT_ADMIT_CARDS: '/dashboard/student/admit-cards',
  STUDENT_EXAMS: '/dashboard/student/exams',
  STUDENT_PROFILE: '/dashboard/student/profile',
  ADMIN_DASHBOARD: '/dashboard/admin',
};
